version: 0.2
phases:
  install:
    commands:
      - cd static
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - npm run-script build
  post_build:
    commands:
      - serverless deploy --stage dev