AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CodePipeline for js-power-site

Parameters:
  GitHubOAuthToken:
    Type : String
    Default: CodepipeGitHubToken
  GitHubUserName:
    Type: String
    Default: mcred89
  GitRepo:
    Type: String
    Default: js-power-site
  GitBranch:
    Type: String
    AllowedValues: 
      - develop
      - master
  BuildSpec:
    Type: String
    AllowedValues: 
      - buildspec-dev.yaml
      - buildspec-prod.yaml

Resources:
  Pipeline: 
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      RoleArn: !GetAtt CodePipelineIAMRole.Arn
      Stages: 
        - Name: GitPull
          Actions: 
            - Name: GitPull
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts: 
                - Name: GitOutput
              Configuration: 
                Owner: !Ref GitHubUserName
                OAuthToken: !GetAtt SecretGetter.secret
                Repo: !Ref GitRepo
                Branch: !Ref GitBranch
              RunOrder: 1
        - Name: Build
          Actions: 
            - Name: Build
              InputArtifacts: 
                - Name: GitOutput
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration: 
                ProjectName: !Ref CodeBuildAndDeploy
      ArtifactStore: 
        Type: S3
        Location: !Ref ArtifactStore

  CodeBuildAndDeploy:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !Ref CodeBuildIAMRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.1.0-1.5.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub 'pipeline/${BuildSpec}'
      TimeoutInMinutes: 10

  ArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-artifact-bucket'
      AccessControl: Private

  CodeBuildIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: build
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:*
                  - cloudformation:*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
                Effect: Allow

  CodePipelineIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: pipe
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - iam:PassRole
                Resource: "*"
                Effect: Allow
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - cloudformation.amazonaws.com
                      - elasticbeanstalk.amazonaws.com
                      - ec2.amazonaws.com
              - Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource: "*"
                Effect: Allow
              - Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Resource: "*"
                Effect: Allow
              - Action:
                  - elasticbeanstalk:*
                  - ec2:*
                  - elasticloadbalancing:*
                  - autoscaling:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                  - cloudformation:*
                  - rds:*
                  - sqs:*
                  - ecs:*
                Resource: "*"
                Effect: Allow
              - Action:
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                Resource: "*"
                Effect: Allow
              - Action:
                  - opsworks:CreateDeployment
                  - opsworks:DescribeApps
                  - opsworks:DescribeCommands
                  - opsworks:DescribeDeployments
                  - opsworks:DescribeInstances
                  - opsworks:DescribeStacks
                  - opsworks:UpdateApp
                  - opsworks:UpdateStack
                Resource: "*"
                Effect: Allow
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                Resource: "*"
                Effect: Allow
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: "*"
                Effect: Allow
              - Effect: Allow
                Action:
                  - servicecatalog:ListProvisioningArtifacts
                  - servicecatalog:CreateProvisioningArtifact
                  - servicecatalog:DescribeProvisioningArtifact
                  - servicecatalog:DeleteProvisioningArtifact
                  - servicecatalog:UpdateProduct
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource: "*"

  SecretsIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: secrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:*
                  - logs:*
                  - secretsmanager:GetSecretValue
                Resource: "*"
                Effect: Allow

  SecretsLambda:
    Type: AWS::Lambda::Function
    Properties: 
      Handler: index.handler
      Role: !GetAtt SecretsIAMRole.Arn
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          SECRET_NAME: !Ref GitHubOAuthToken
      Code: 
        ZipFile: |
          var AWS = require('aws-sdk');
          var region = process.env.REGION;
          var secretName = process.env.SECRET_NAME;
          var secret;
          var responseData;
          var client = new AWS.SecretsManager({
              region: region
          });
          var response = require('cfn-response');
          exports.handler = function(event, context) {
              if (event.RequestType == 'Delete') {
                  response.send(event, context, response.SUCCESS);
                  return;
              }
              client.getSecretValue({SecretId: secretName}, function(err, data) {
                  if (err) {
                      response.send(event, context, response.FAILED);
                      throw err;
                  } else {
                      secret_dict = JSON.parse(data['SecretString']);
                      secret = secret_dict[secretName]
                      responseData = {'secret': secret}
                      response.send(event, context, response.SUCCESS, responseData);
                  }
              });
          }
      Runtime: nodejs8.10
      Timeout: 60

  SecretGetter:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt SecretsLambda.Arn
